name: Jest Test

on: 
  pull_request:
    branches:
      - master

jobs:
  test-coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - run: npm ci
      - run: npm run test:ci